# Generated by Django 5.0.6 on 2024-06-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='dateCreation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
